
services:
  # https://docs.docker.com/reference/compose-file/services/
  database:
    container_name: prom-dev
    build:
      context: .
      dockerfile: Dockerfile
      target: database
    restart: always # unless-stopped
    env_file:
      - .env
    volumes:
      #- ./cache/postgres/data:/var/lib/postgresql/data
      - ./cache/postgres:/var/lib/postgresql
    ports:
      - "5432:5432"
    # https://stackoverflow.com/questions/57015003/log-all-queries-in-the-official-postgres-docker-image
    command: [
      "postgres",
      # https://www.postgresql.org/docs/current/runtime-config-logging.html
      "-c",
      #"log_statement=all",
      "log_statement=mod",
#       "-c",
#       "log_min_error_statement=WARNING",
#       "-c",
#       "log_min_messages=WARNING",
#       "-c",
#       "log_error_verbosity=TERSE",
      "-c",
      #"log_min_duration_statement=2000"
      "log_min_duration_statement=0"
    ]


